name: CI - Test Action

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action
        id: test-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
        with:
          config_file: './.github/commitlint.js'

      - name: Print Output
        id: output
        run: echo "valid => ${{ steps.test-action.outputs.valid }}"
      - run: echo "skiiped => ${{ steps.test-action.outputs.skipped }}"
      - run: echo "number => ${{ steps.test-action.outputs.pr_number }}"
      - run: echo "title => ${{ steps.test-action.outputs.pr_title }}"
      - run: echo "report => ${{ steps.test-action.outputs.report }}"
      - run: echo "outcomes => ${{ steps.test-action.outputs.outcomes }}"

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.test-action.outputs.valid == 'false')
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.test-action.outputs.report }}
            ```

        # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.test-action.outputs.valid == 'true' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
