name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup bun
        id: setup-bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        id: bun-ci
        run: bun install

      - name: Static analysis
        id: bun-format-check
        run: bun check

      - name: Test
        id: bun-ci-test
        run: bun ci-test
